### ISSUE TITLE
Library name

### ISSUE THREAD

**Issue by Sibyx** [Sibyx/django_request_formatter#4]
I am not very proud of naming library `django_requests_formatter` because is not very accurate (To be honest, I think that  name doesn't make any sense).

I am opening this issue to collect potential library names. It's much more easier to rename library in this stage of development before major release.

List of potential names:

- `django_api_forms`
- `django_rest_forms`

**Comment by zurek11** [comment]
django_nested_forms?

**Comment by Sibyx** [comment]
We are going to use `django_api_forms`
